name: Hello World

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "¡Hola mundo!"

      - name: Show date
        run: date

      - name: List directory
        run: ls -l
