name: Deployment pipeline

on:
  push:
    branches:
      - main
      

  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Check style
        run: npm run eslint

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Test e2e
        run: npm run test:e2e

      - name: Trigger deployment1
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: curl "$RENDER_DEPLOY_HOOK_URL"

      - name: Notify Discord
        if: always()
        run: |
          curl -H "Content-Type: application/json" \
            -d '{"content":"GitHub Actions: ${{ github.workflow }} terminó con estado ${{ job.status }} en ${{ github.ref }}"}' \
            ${{ secrets.DISCORD_WEBHOOK }}


  tag_release:
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
